import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "@/app/ui/navbar/navbar";
import Footer from "./ui/footer/footer";


const epilogue = localFont({
  src: '../../public/fonts/epilogue/fonts/Epilogue-Variable.woff2',
  display: "swap"
})

export const metadata: Metadata = {
  title: "Synergia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`relative flex flex-col items-center h-screen w-screen overflow-x-hidden overflow-y-scroll text-lg bg-white text-black font-normal text-center ${epilogue.className}`} >
        <Navbar />
        <main className="flex flex-col items-center justify-center w-full pb-72">
          {children}
        </main>
          <Footer />
      </body>
    </html>
  );
}
