import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "@/app/ui/navbar/navbar";
import Footer from "./ui/footer/footer";


const inter = Inter({ subsets: ["latin"] });
const epilogue = localFont({
  src: '../../public/fonts/epilogue/fonts/Epilogue-Variable.woff2',
  display: "swap"
})

export const metadata: Metadata = {
  title: "Synergia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`flex flex-col items-center h-screen w-screen overflow-x-hidden text-lg font-medium gap-y-36 lg:gap-y-44 ${epilogue.className}`} >
        <Navbar />
        <main className="flex flex-col items-center justify-center w-10/12 bg-black">
          {children}
        </main>
          <Footer />
      </body>
    </html>
  );
}
